name: GitHub Classroom Workflow

on:
  push:
    branches: [ main, 'feature/**', 'sugerencia/**' ]
  pull_request:
    branches: [ feedback ]

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: education/autograding@v1
